apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: tutorial-tools
      labels:
        app.kubernetes.io/name: tutorial-tools
        app.kubernetes.io/component: workshop
        app.kubernetes.io/part-of: rhd-workshops
    spec:
      securityContext:
        runAsUser: 1001    
      containers:
      - name: tutorial-tools
        image: quay.io/rhdevelopers/tutorial-tools:0.0.1
        imagePullPolicy: IfNotPresent
        env:
         - name: MAVEN_MIRROR_URL
           value: 'http://nexus.rhd-workshop-infra:8081/nexus/content/groups/public'
        # securityContext:
        #   runAsUser: 1001
        workingDir: /home/developer
        resources:
          limits: 
            cpu: 4
            memory: 6Gi
          requests:
            cpu: 2
            memory: 4Gi
        command:
          - '/usr/local/bin/run.sh'
        args:
          - 'sleep'
          - 'infinity'
  - apiVersion: v1
    kind: Pod
    metadata:
      name: tutorial-clients
      labels:
        app.kubernetes.io/name: clients
        app.kubernetes.io/component: workshop
        app.kubernetes.io/part-of: rhd-workshops
    spec:
      containers:
      - name: clients
        image: 'quay.io/rhdevelopers/clients:0.0.1'
        imagePullPolicy: IfNotPresent
        resources:
          limits: 
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512m"
        securityContext:
          runAsUser: 1001
        workingDir: /home/developer