apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Pod
  metadata:
    name: tutorial-tools
    labels:
      app: tutorial-tools
  spec:
    containers:
    - name: tutorial-tools
      image: quay.io/rhdevelopers/tutorial-tools:0.0.2
      imagePullPolicy: IfNotPresent
      env:
        - name: MAVEN_MIRROR_URL
          value: 'http://nexus.rhd-workshop-infra:8081/nexus/content/groups/public'
      workingDir:  /projects
      resources:
        limits: 
          cpu: 2
          memory: 2Gi
        requests:
          cpu: 1
          memory: 1Gi
- apiVersion: v1
  kind: Pod
  metadata:
    name: tutorial-clients
    labels:
      app: tutorial-clients
  spec:
    containers:
    - name: tutorial-clients
      image: 'quay.io/rhdevelopers/clients:0.0.1'
      imagePullPolicy: IfNotPresent
      resources:
        limits: 
          cpu: "1"
          memory: "1Gi"
        requests:
          cpu: "0.5"
          memory: "512m"
      workingDir:  /projects
- apiVersion: v1
  kind: Pod
  metadata:
    name: container-tools
    labels:
      app: container-tools
  spec:
    containers:
    - name: container-tools
      image: 'quay.io/rhdevelopers/container-tools:0.0.1'
      imagePullPolicy: IfNotPresent
      resources:
        limits: 
          cpu: "1"
          memory: "1Gi"
        requests:
          cpu: "0.5"
          memory: "512m"
      workingDir:  /projects