runtime:
  cache_dir: ./.cache/antora

site:
  title: Severless and Servicemesh with OpenShift::Workshops
  url: https://dnl-blr-staging.web.app/
  start_page: summit-guru-night::index.adoc

content:
  sources:
    # - url: https://github.com/redhat-developer-demos/guru-night
    #   branches: master
    #   start_path: documentation
    - url: https://github.com/redhat-developer-demos/openshift-basics
      branches: master
    # - url: https://github.com/redhat-developer-demos/istio-tutorial
    #   branches:  dnl/blr-2019
    #   start_path: documentation
    # - url: https://github.com/redhat-developer-demos/knative-tutorial-module-basics
    #   branches: dnl/blr-2019
asciidoc:
  attributes:
    title: Introduction to Containers and Kubernetes
    workshop: true
    etherpad-url: https://etherpad.wikimedia.org/p/sgnog19
    etherpad: https://etherpad.wikimedia.org/p/sgnog19
    namespace-suffix: -$WORKSHOP_USER
    appdomain: apps.cluster-sin-257f.sin-257f.openshiftworkshop.com
    tutorial-namespace: $WORKSHOP_USER-knativetutorial
    ocpurl: https://api.cluster-sin-257f.sin-257f.openshiftworkshop.com:6443      
    workshop-domain: cluster-sin-257f.sin-257f.openshiftworkshop.com
    workshop-version: release/0.5 
    path: customer$WORKSHOP_USER
    openshift-console-url: http://console-openshift-console.apps.cluster-sin-257f.sin-257f.openshiftworkshop.com
  extensions:
    - ./lib/copy-to-clipboard.js
    - ./lib/tab-block.js
ui:
  bundle:
    url: https://github.com/redhat-developer-demos/rhd-tutorial-ui/releases/download/v0.0.4/ui-bundle.zip
  supplemental_files: ./supplemental-ui
output:
  dir: ./gh-pages
