runtime:
  cache_dir: ./.cache/antora

site:
  title: DevNationLive Bengaluru::Workshops
  url: https://dnl-blr-2019.devx.red
  start_page: summit-guru-night::index.adoc

content:
  sources:
    - url: https://github.com/redhat-developer-demos/guru-night
      branches: master
      start_path: documentation
    - url: https://github.com/redhat-developer-demos/openshift-basics
      branches: master
    - url: https://github.com/redhat-developer-demos/istio-tutorial
      branches:  dnl/blr-2019
      start_path: documentation
    - url: https://github.com/redhat-developer-demos/knative-tutorial-module-basics
      branches: dnl/blr-2019
asciidoc:
  attributes:
    title: DevNationLive Bengaluru::Workshops
    workshop: true
    etherpad-url: https://etherpad.wikimedia.org/p/DNLBlr19
    etherpad: https://etherpad.wikimedia.org/p/DNLBlr19
    namespace-suffix: -$WORKSHOP_USER
    appdomain: apps.guru.devx.red
    tutorial-namespace: $WORKSHOP_USER-knativetutorial
    ocpurl: https://api.guru.devx.red:6443       
    workshop-domain: guru.devx.red
    workshop-version: release/0.5 
    path: customer$WORKSHOP_USER
    openshift-console-url: http://example.com
  extensions:
    - ./lib/copy-to-clipboard.js
    - ./lib/tab-block.js
ui:
  bundle:
    url: https://github.com/redhat-developer-demos/rhd-tutorial-ui/releases/download/v0.0.4/ui-bundle.zip
  supplemental_files: ./supplemental-ui
output:
  dir: ./gh-pages
