runtime:
  cache_dir: ./.cache/antora

site:
  title: Summit Guru Night
  url: https://summit-guru-night.devx.red
  start_page: summit-guru-night::index.adoc

content:
  sources:
    - url: https://github.com/redhat-developer-demos/guru-night
      branches: master
      start_path: documentation
    - url: https://github.com/redhat-developer-demos/istio-tutorial
      branches:  workshop/sin-052019
      start_path: documentation
    - url: https://github.com/redhat-developer-demos/knative-tutorial-module-basics
      branches: workshop/0.5
      start_path: documentation

asciidoc:
  attributes:
    title: Summit Guru Night
    istio-tutorial-namespace: $WORKSHOP_USER-istiotutorial
    tutorial-namespace: $WORKSHOP_USER-knativetutorial
    workshop: true
    ocpurl:
       - https://api.guru.devx.red:6443
       - https://example.com
    master-urls:
      - http://example.com
      - ttp://example.org
    appdomain: apps.guru.devx.red
    etherpad: https://etherpad.wikimedia.org/p/DevOpsCon
    namespace-suffix: -$WORKSHOP_USER
    workshop-domain: guru.devx.red
    workshop-version: release/0.4
  extensions:
    - ./lib/copy-to-clipboard.js
ui:
  bundle:
    url: https://github.com/redhat-developer-demos/rhd-tutorial-ui/releases/download/v0.0.3/ui-bundle.zip
  supplemental_files: ./supplemental-ui
output:
  dir: ./gh-pages
