apiVersion: v1
kind: LimitRange
metadata:
  name: tutorials-mem-cpu-limit-range
spec:
  limits:
  - default:
     cpu: "250m"
     memory: "756Mi"
    defaultRequest:
     cpu: "100m"
     memory: "256Mi"    
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: tutorials-resource-quota
spec:
  hard:
    pods: 4
    requests.cpu: "1000m"
    requests.memory: "1512Mi"
    limits.cpu: "2500m"
    limits.memory: "3024Mi"