apiVersion: v1
kind: LimitRange
metadata:
  name: tutorials-mem-cpu-limit-range
spec:
  limits:
  - default:
     cpu: "250m"
     memory: "756Mi"
    defaultRequest:
     cpu: "100m"
     memory: "256Mi"    
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: tutorials-resource-quota
spec:
  hard:
    pods: 6
    requests.cpu: "1100m"
    requests.memory: "2000Mi"
    limits.cpu: "3000m"
    limits.memory: "5120Mi"