apiVersion: v1
kind: LimitRange
metadata:
  name: tutorials-mem-cpu-limit-range
spec:
  limits:
  - default:
     cpu: "200m"
     memory: "256Mi"
    defaultRequest:
     cpu: "100m"
     memory: "128Mi"    
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: tutorials-resource-quota
spec:
  hard:
    pods: 6
    requests.cpu: "940m"
    requests.memory: "1576Mi"
    limits.cpu: "4"
    limits.memory: "5Gi"